# Generated by Django 5.0.4 on 2024-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.CharField(default='test1', max_length=30),
            preserve_default=False,
        ),
    ]
