# Generated by Django 5.0.4 on 2024-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='community_picture/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
