# Generated by Django 5.0.4 on 2024-04-27 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_community_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('community', models.CharField(max_length=100)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(default='Awesome community', max_length=300),
            preserve_default=False,
        ),
    ]
