# Generated by Django 5.0.4 on 2024-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_community_community_photo_alter_posts_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySpecificTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=300)),
                ('template_dict', models.CharField(max_length=10000)),
            ],
        ),
    ]
