# Generated by Django 5.0.4 on 2024-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_communityspecifictemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AddField(
            model_name='posts',
            name='template_dict',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='template_name',
            field=models.CharField(default='Default Template', max_length=100),
            preserve_default=False,
        ),
    ]
