# Generated by Django 5.0.4 on 2024-04-27 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usercommunitymembership_community_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('location', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('community_name', models.CharField(max_length=100)),
                ('author_username', models.CharField(max_length=30)),
            ],
        ),
    ]
