# Generated by Django 5.0.4 on 2024-04-27 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_defaulttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttemplate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='defaulttemplate',
            name='location',
        ),
        migrations.AddField(
            model_name='defaulttemplate',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
