# Generated by Django 5.0.4 on 2024-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_posts_content_remove_posts_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='template_dict',
            field=models.JSONField(),
        ),
    ]
