# Generated by Django 5.0.4 on 2024-04-28 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_defaulttemplate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='defaulttemplate',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
