# Generated by Django 5.0.4 on 2024-05-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_defaulttemplate_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultTemplate',
            new_name='Posts',
        ),
    ]
