# Generated by Django 5.0.4 on 2024-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('about_me', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_picture', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
