# Generated by Django 5.0.4 on 2024-04-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestOvunc',
            new_name='OvuncTable',
        ),
    ]
